import { Category, Product, DeliveryZone } from '../types';
import { DEFAULT_DELIVERY_ZONES } from '../config/constants';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-vasos',
    name: 'Helados en Vasos',
    slug: 'helados-en-vasos',
    description: 'Porciones individuales cremosas servidas en vasos térmicos con toppings.',
    icon: 'IceCream',
    image_url: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&auto=format&fit=crop&q=80',
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cat-tinas',
    name: 'Tinas 4.5 Litros',
    slug: 'tinas-4-5-litros',
    description: 'Tinas familiares de 4.5 Litros ideales para compartir y fiestas en Puerto Padre.',
    icon: 'Container',
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80',
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cat-cakes',
    name: 'Cakes',
    slug: 'cakes',
    description: 'Tartas y cakes artesanales con merengue italiano, crema chantilly y chocolate.',
    icon: 'Cake',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cat-combos',
    name: 'Combos',
    slug: 'combos',
    description: 'Paquetes especiales que combinan helados, dulces y refrescos con descuento.',
    icon: 'Sparkles',
    image_url: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    display_order: 4,
    is_active: true,
  },
  {
    id: 'cat-dulceria',
    name: 'Dulcería',
    slug: 'dulceria',
    description: 'Eclairs, tartaletas de frutas, marquesitas, brownies y polvorones recién horneados.',
    icon: 'Cookie',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    display_order: 5,
    is_active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. Helados en Vasos
  {
    id: 'prod-copa-caram',
    category_id: 'cat-vasos',
    name: 'Copa Suprema Caram',
    slug: 'copa-suprema-caram',
    description: 'Dos bolas de helado artesanal de dulce de leche y mantecado, coronadas con sirope de caramelo espeso y almendras tostadas.',
    price: 3.5,
    previous_price: 4.2,
    sku: 'VAS-001',
    stock: 45,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Vaso térmico 12oz',
    flavors: ['Caramelo & Mantecado', 'Fresa & Vainilla', 'Chocolate & Nuez', 'Pistacho'],
  },
  {
    id: 'prod-vaso-fresas-crema',
    category_id: 'cat-vasos',
    name: 'Vaso Fresa Salvaje & Nata',
    slug: 'vaso-fresa-salvaje-nata',
    description: 'Helado cremoso de fresas naturales con trozos de fruta macerada y espiral de crema chantilly.',
    price: 3.0,
    previous_price: null,
    sku: 'VAS-002',
    stock: 30,
    image_url: 'https://images.unsplash.com/photo-1488900128323-21503983a07e?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Vaso térmico 10oz',
    flavors: ['Fresa natural', 'Frutos del Bosque'],
  },
  {
    id: 'prod-vaso-cacao-intenso',
    category_id: 'cat-vasos',
    name: 'Vaso Cacao Baracoa 70%',
    slug: 'vaso-cacao-baracoa-70',
    description: 'Puro chocolate cubano con chispas crujientes de chocolate amargo y lluvia de avellanas.',
    price: 3.2,
    previous_price: null,
    sku: 'VAS-003',
    stock: 25,
    image_url: 'https://images.unsplash.com/photo-1579954115545-a95591f28be0?w=600&auto=format&fit=crop&q=80',
    is_featured: false,
    is_available: true,
    unit: 'Vaso térmico 10oz',
    flavors: ['Chocolate Belga', 'Cacao Cubano'],
  },

  // 2. Tinas 4.5 Litros
  {
    id: 'prod-tina-mantecado-familiar',
    category_id: 'cat-tinas',
    name: 'Tina Familiar 4.5L Mantecado Clásico',
    slug: 'tina-4-5l-mantecado-clasico',
    description: 'El sabor tradicional más aclamado de Helados Caram. Textura ultra suave con extracto de vainilla y toque de canela.',
    price: 18.0,
    previous_price: 21.0,
    sku: 'TIN-001',
    stock: 12,
    image_url: 'https://images.unsplash.com/photo-1580915411954-282cb1b0d780?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Tina hermética 4.5 Litros',
    flavors: ['Mantecado tradicional'],
  },
  {
    id: 'prod-tina-combinada-tres-sabores',
    category_id: 'cat-tinas',
    name: 'Tina 4.5L Napolitana Trío Especial',
    slug: 'tina-4-5l-napolitana-trio',
    description: 'Tres secciones perfectas de Chocolate, Fresa y Dulce de Leche Caram en un formato ideal para reuniones familiares.',
    price: 20.0,
    previous_price: 23.5,
    sku: 'TIN-002',
    stock: 8,
    image_url: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Tina hermética 4.5 Litros',
    flavors: ['Chocolate - Fresa - Caramelo'],
  },
  {
    id: 'prod-tina-mango-coco',
    category_id: 'cat-tinas',
    name: 'Tina 4.5L Tropical Mango & Coco Rallado',
    slug: 'tina-4-5l-mango-coco',
    description: 'Refrescante crema de mango de la región oriental con vetas de leche de coco y ralladura tostada.',
    price: 19.0,
    previous_price: null,
    sku: 'TIN-003',
    stock: 6,
    image_url: 'https://images.unsplash.com/photo-1516559828984-fb3b99548b21?w=600&auto=format&fit=crop&q=80',
    is_featured: false,
    is_available: true,
    unit: 'Tina hermética 4.5 Litros',
    flavors: ['Mango & Coco Tropical'],
  },

  // 3. Cakes
  {
    id: 'prod-cake-tres-leches-caram',
    category_id: 'cat-cakes',
    name: 'Cake Tres Leches con Relleno de Caramelo',
    slug: 'cake-tres-leches-caram',
    description: 'Bizcocho esponjoso bañado en tres leches enriquecidas, relleno de dulce de leche artesanal y cubierto de merengue dorado suave.',
    price: 22.0,
    previous_price: 25.0,
    sku: 'CAK-001',
    stock: 10,
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Cake para 15-18 personas',
  },
  {
    id: 'prod-cake-selva-negra',
    category_id: 'cat-cakes',
    name: 'Cake Selva Negra & Cerezas',
    slug: 'cake-selva-negra-cerezas',
    description: 'Bizcocho de chocolate húmedo con capas de crema chantilly, compota de cerezas y virutas de chocolate semiamargo.',
    price: 24.0,
    previous_price: null,
    sku: 'CAK-002',
    stock: 5,
    image_url: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&auto=format&fit=crop&q=80',
    is_featured: false,
    is_available: true,
    unit: 'Cake para 16 personas',
  },
  {
    id: 'prod-cake-helado-personalizado',
    category_id: 'cat-cakes',
    name: 'Cake Helado Artesanal Cumpleaños',
    slug: 'cake-helado-artesanal-cumpleanos',
    description: 'Base crujiente de galleta y bizcocho con capas de helado de mantecado y fresa, decorado con merengue suizo. Incluye mensaje personalizado.',
    price: 28.0,
    previous_price: 32.0,
    sku: 'CAK-003',
    stock: 4,
    image_url: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Cake helado 20 personas',
  },

  // 4. Combos
  {
    id: 'prod-combo-dulce-fiesta',
    category_id: 'cat-combos',
    name: 'Combo Dulce Fiesta Puerto Padre',
    slug: 'combo-dulce-fiesta-puerto-padre',
    description: 'Incluye 1 Tina de 4.5L a elección + 6 Vasos térmicos + 1 Bandeja de 12 Marquesitas surtidas + Siropes de regalo.',
    price: 32.0,
    previous_price: 38.0,
    sku: 'COM-001',
    stock: 15,
    image_url: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Combo Completo',
  },
  {
    id: 'prod-combo-tarde-antojo',
    category_id: 'cat-combos',
    name: 'Combo Tarde de Antojo (Para 2)',
    slug: 'combo-tarde-antojo-pareja',
    description: '2 Copas Supremas + 2 Brownies de chocolate con nuez + 2 Refrescos fríos.',
    price: 11.5,
    previous_price: 13.5,
    sku: 'COM-002',
    stock: 20,
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    is_featured: false,
    is_available: true,
    unit: 'Combo Pareja',
  },

  // 5. Dulcería
  {
    id: 'prod-marquesitas-caramelo',
    category_id: 'cat-dulceria',
    name: 'Caja de Marquesitas Rellenas (6 uds)',
    slug: 'caja-marquesitas-rellenas',
    description: 'Deliciosas marquesitas de masa fina rellenas con dulce de leche Caram y espolvoreadas con azúcar nevada.',
    price: 4.5,
    previous_price: null,
    sku: 'DUL-001',
    stock: 40,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    is_featured: true,
    is_available: true,
    unit: 'Caja x 6 unidades',
  },
  {
    id: 'prod-tartaleta-frutas',
    category_id: 'cat-dulceria',
    name: 'Tartaleta Glaseada de Frutas Frescas',
    slug: 'tartaleta-glaseada-frutas',
    description: 'Masa sableé crocante con crema pastelera aromatizada con piel de limón y frutas de temporada glaseadas.',
    price: 2.2,
    previous_price: null,
    sku: 'DUL-002',
    stock: 25,
    image_url: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=80',
    is_featured: false,
    is_available: true,
    unit: 'Unidad individual',
  },
  {
    id: 'prod-brownie-fudge',
    category_id: 'cat-dulceria',
    name: 'Brownie Fudge con Nuez & Caramelo Salado',
    slug: 'brownie-fudge-nuez-caramelo',
    description: 'Interior meloso de chocolate oscuro, nueces crujientes y finos hilos de caramelo al toque de sal marina.',
    price: 2.5,
    previous_price: null,
    sku: 'DUL-003',
    stock: 30,
    image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    is_featured: false,
    is_available: true,
    unit: 'Porción 120g',
  },
];
